### ISSUE TITLE
[Performance]: implement local cache

### ISSUE THREAD

**Issue by sbayd** [jotform/zenith#44]
I see some PRs are already successfully built when they are in queue, when it gets to "merging" status it downloads all previously builded files from aws which takes almost 1mins. We can reduce this to milliseconds by using a local-first cache. We know the pr is already built on the local folder in the same agent-machine.

What do you think?

**Comment by hmdoganjf** [comment]
Implemented with [v1.0.0](https://github.com/jotform/zenith/releases/tag/v1.0.0)
